name: pdediff
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - h5py=3.7.0
  - jupyter=1.0.0
  - numpy=1.23.5
  - pip=22.3.1
  - python=3.9.16
  - pytorch=2.1.0 #pytorch=1.13.1
  - pytorch-cuda=11.7
  - pip:
    - dawgz==0.4.1
    - jax
    - jaxlib
    - matplotlib==3.6.2
    - POT==0.9.0
    - seaborn==0.12.2
    - tqdm==4.64.1
    - zuko
    - hydra_core==1.3.2
    - hydra_colorlog==1.2.0
    - hydra_colorlog==1.2.0
    - hydra_joblib_launcher==1.1.5
    - hydra-submitit-launcher==1.2.0
    - fsspec==2023.6.0
    - wandb
    - einops==0.7.0
    - gdown
